In [2]:
from sklearn.datasets import make_classification
import torch


In [3]:
X,y = make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [4]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [7]:
X_tensor = torch.Tensor(X)
Y_tensor = torch.Tensor(y)
X_tensor.to(torch.device('cuda'))
Y_tensor.to(torch.device('cuda'))

tensor([1., 0., 0., 0., 0., 1., 1., 1., 1., 0.], device='cuda:0')

In [8]:
from torch.utils.data import DataLoader,Dataset


In [9]:
class CustomDataset(Dataset):
    def __init__(self,features, label):
        self.features = features
        self.label = label
    def __len__(self):
        return self.features.shape[0]
    def __getitem__(self, idx):
        return self.features[idx], self.label[idx]


In [10]:
dataset = CustomDataset(X, y)

In [11]:
len(dataset)

10

In [12]:
dataset[0]

(array([ 1.06833894, -0.97007347]), np.int64(1))

In [13]:
dataloader = DataLoader(dataset,batch_size=2,shuffle=True)

In [14]:
for batch_features,batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)

tensor([[ 1.7273, -1.1858],
        [-1.9629, -0.9923]], dtype=torch.float64)
tensor([1, 0])
tensor([[ 1.7774,  1.5116],
        [-0.7206, -0.9606]], dtype=torch.float64)
tensor([1, 0])
tensor([[-2.8954,  1.9769],
        [ 1.0683, -0.9701]], dtype=torch.float64)
tensor([0, 1])
tensor([[-0.9382, -0.5430],
        [-0.5872, -1.9717]], dtype=torch.float64)
tensor([1, 0])
tensor([[-1.1402, -0.8388],
        [ 1.8997,  0.8344]], dtype=torch.float64)
tensor([0, 1])
