In [18]:
from __future__ import print_function
import torch
x = torch.rand(5,3)
print(x)

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588]])


In [19]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available")

GPU is available
Using GPU: NVIDIA GeForce GTX 1650


In [20]:
torch.empty(2,3)

tensor([[ 4.2889e+14,  1.2037e-42,  2.3446e-01],
        [ 2.3033e-01, -1.1229e+00, -1.8633e-01]])

In [21]:
a=torch.zeros(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [22]:
type(a)

torch.Tensor

In [23]:
#manual_seed allows to generate same random values every time code is run
torch.manual_seed(42)
a=torch.randn(2,3)
print(a)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863]])


In [24]:
torch.manual_seed(42)
b=torch.randn(2,3)
print(b)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863]])


In [25]:
#arange
print("using arange ->", torch.arange(0,10,2))

#using linespace equally spaced values between start index and endindex and number of values
print("using linspace ->",torch.linspace(0,10,10))

#using eye : eye stands for identity matrix
print("using eye ->", torch.eye(5))

#using full
print("using full ->", torch.full((2,3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5]])


In [26]:
x += 3

In [27]:
x.to(dtype=torch.int64)

tensor([[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]])

In [28]:
c = torch.tensor([1,2,3,4,5])
c.clamp(min=2,max=3)

tensor([2, 2, 3, 3, 3])

In [29]:
y = torch.tensor([[1.2,2.3,3.4,4.5],[5.6,6.7,7.8,8.9]])
torch.ceil(y)

tensor([[2., 3., 4., 5.],
        [6., 7., 8., 9.]])

In [30]:
z = torch.tensor([[1.2,2.3,3.4,4.5],[5.6,6.7,7.8,8.9]])
print(z)

tensor([[1.2000, 2.3000, 3.4000, 4.5000],
        [5.6000, 6.7000, 7.8000, 8.9000]])


In [32]:
e = torch.randint(size =(2,3), low=0, high=10)
e

tensor([[7, 6, 9],
        [6, 3, 1]])

In [35]:
torch.sum(e)
#sum of the entire tensor

tensor(32)

In [36]:
torch.sum(e,dim=0)
#sum along the columns

tensor([13,  9, 10])

In [37]:
torch.sum(e,dim =1)

tensor([22, 10])

In [42]:
torch.matmul(e,torch.transpose(e,0,1))

tensor([[166,  69],
        [ 69,  46]])

In [44]:
f = torch.tensor([-2,-1,0,1,2],dtype=torch.float32)
torch.sigmoid(f)


tensor([0.1192, 0.2689, 0.5000, 0.7311, 0.8808])

In [45]:
torch.relu(f)

tensor([0., 0., 0., 1., 2.])

In [47]:
torch.tanh(f)

tensor([-0.9640, -0.7616,  0.0000,  0.7616,  0.9640])

In [48]:
e =f.clone()

In [49]:
id(e)

1398703541376

In [50]:
id(f)

1398703737984

In [55]:
device = torch.device('cuda')
x = torch.rand((2,3), device=device)

In [56]:
id(x)

1398555242608

In [62]:
import time
size = 15000
matrix_cpu1 = torch.randn(size,size)
matrix_cpu2 = torch.randn(size,size)
start_time = time.time()
result= torch.matmul(matrix_cpu1,matrix_cpu2)
end_time = time.time()
print(f"Time on CPU: {end_time - start_time:.4f} seconds")

matrix_cpu1 = matrix_cpu1.to('cuda')
matrix_cpu2 = matrix_cpu2.to('cuda')

start_time = time.time()
result = torch.matmul(matrix_cpu1,matrix_cpu2)
torch.cuda.synchronize()
end_time = time.time()

print(f"Time on GPU: {end_time - start_time:.4f} seconds")


Time on CPU: 35.4662 seconds
Time on GPU: 4.4751 seconds
