In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(arr1.shape)
print(arr1.dtype)


[1 2 3 4 5]
(5,)
int32


In [4]:
arr2 = np.array([6,7,8,9,10])
arr3 = arr1*arr2
print(arr3)


[ 6 14 24 36 50]


In [5]:
arr4 = np.array([1,2,3,4,5])
print(arr4*2)

[ 2  4  6  8 10]


In [6]:
print(arr1+arr2)

[ 7  9 11 13 15]


In [7]:
arr4.ndim

1

In [8]:
arr6 = np.array([[1,2,3],[4,5,6]])
print(arr6)

[[1 2 3]
 [4 5 6]]


In [9]:
arr6.ndim

2

In [12]:
arr6.mean()

3.5